"""Лимиты для административных операций."""

ADMIN_MAX_WITHDRAWALS_PER_DAY = 50
ADMIN_MAX_WITHDRAWAL_AMOUNT_PER_DAY_USDT = 50000.0
ADMIN_MAX_BALANCE_ADJUSTMENTS_PER_WEEK = 20
ADMIN_MAX_BANS_PER_HOUR = 20
ADMIN_MAX_TERMINATIONS_PER_HOUR = 20
ADMIN_MAX_WITHDRAWAL_APPROVALS_PER_HOUR = 50
ADMIN_MAX_LARGE_WITHDRAWAL_APPROVALS_PER_HOUR = 10
ADMIN_LARGE_WITHDRAWAL_THRESHOLD_USDT = 1000.0
DUAL_CONTROL_WITHDRAWAL_THRESHOLD_USDT = 1000.0
DUAL_CONTROL_ESCROW_EXPIRY_HOURS = 24
