"""
Admin Service - Constants.

Configuration constants for admin authentication and session management.
"""

from app.config.constants import (
    ADMIN_SESSION_DURATION_HOURS,
    ADMIN_MASTER_KEY_LENGTH,
    ADMIN_LOGIN_MAX_ATTEMPTS as CONFIG_ADMIN_LOGIN_MAX_ATTEMPTS,
    ADMIN_LOGIN_WINDOW_SECONDS as CONFIG_ADMIN_LOGIN_WINDOW_SECONDS,
)

# Admin session configuration
SESSION_DURATION_HOURS = ADMIN_SESSION_DURATION_HOURS

# Master key configuration
MASTER_KEY_LENGTH = ADMIN_MASTER_KEY_LENGTH

# Admin login rate limiting
ADMIN_LOGIN_MAX_ATTEMPTS = CONFIG_ADMIN_LOGIN_MAX_ATTEMPTS
ADMIN_LOGIN_WINDOW_SECONDS = CONFIG_ADMIN_LOGIN_WINDOW_SECONDS
